### ISSUE TITLE
[Potential BUG] Solidity version not being read correctly

### ISSUE THREAD

**Issue by jmartinez-43** [quantstamp/qsp-protocol-node#465]
<h2> Quick Summary of Issue </h2>
Quantstamp protocol is not accepting a scan from a smart contract with a pragma of `pragma solidity >=0.4.26 <0.5.0;` even though the app is supposed to be compatible with Solidity versions 0.4.5 - 0.5.4. 

<h2>Details</h2>
When I attempt to scan the contract,  I received the following error message from the UI:

> Compilation failed, please check your code. Solidity version is not supported by the Quantstamp Protocol.

[Click here](https://etherscan.io/address/0xf1BFe5b1c2332CeD7D18DDB3A52eF9B512399e97#code) to view the smart contract code on Etherscan. 

Also, the smart contract code was successfully verified by Etherscan. 

<h2>Hypothesis</h2>
I think the error is occuring because our protocol is not correctly reading the pragma version of the smart contract. It probably expects only to see `pragma solidity ^0.4.26` and not `pragma solidity >=0.4.26 <0.5.0`

**Comment by alex-murashkin** [comment]
Hey Julian, thanks for reporting this! This is a known limitation, and I believe @martinetlee is working on adding such a support to `usolc`. Will keep you posted!

**Comment by martinetlee** [comment]
```Quantstamp protocol is not accepting a scan from a smart contract with a pragma of `pragma solidity >=0.4.26 <0.5.0;` even though the app is supposed to be compatible with Solidity versions 0.4.5 - 0.5.4.```

The pragma requires that the betanet-ui to summon `0.4.26` which is not supported by the UI currently.  (`0.4.26` is actually a new release that came after `0.5.4` )

**Comment by jmartinez-43** [comment]
Makes sense. I missed that.

**Comment by martinetlee** [comment]
Closing the issue since the question is resolved, the support of 0.4.26 will be live after https://github.com/quantstamp/universal-solc-compiler/pull/30 is merged and pushed into qsp-protocol-node production.
