### ISSUE TITLE
Audit request 30 resulted in a verification state deemed incorrect, not clear why

### ISSUE THREAD

**Issue by bbruijn** [quantstamp/qsp-protocol-node#480]
## Expected Behavior

My node has been up for a week now with 1 succesful scan (request id 26) 

## Current Behavior

Today a second audit request was assigned to my node (request id 30) but it resulted in a verification state: deemed incorrect.

## Steps to Reproduce

1.
2.
3.
4.

## Context

I'm trying to run a stable node but now its unclear what went wrong and what I can do to prevent this in the future.

## Your Environment

* Version of this software:
v2.0.2-alpha2

* Operating System and version:
![Schermafbeelding 2019-06-01 om 23 03 17](https://user-images.githubusercontent.com/11259481/58753708-05f66100-84c4-11e9-8278-e406c001cc53.png)
## Additional Comments

[terminaluitvoer.log](https://github.com/quantstamp/qsp-protocol-node/files/3244225/terminaluitvoer.log)

**Comment by alex-murashkin** [comment]
Hey @bbruijn ,

We are looking into it right now.
I've been looking into the log file, but I can't see any request ids related to the failed request (30). Only saw the successful 26 one.

Could you take a look into your home directory's `.qsp-protocol` folder, are there any log and tar files? If so, could you zip them and share these all? (we will document the location in the node operator manual for future reference).

**Comment by alex-murashkin** [comment]
Also, we did some digging into the why the report was deemed incorrect looking at the reports stored on-chain.

It looks like the only difference is the status: your node has marked its report as "error" (and we need logs to understand why), while the police node marked its report as "success". However, the findings are exactly the same:

Your node's report:
```
{'analyzers_reports': [{'analyzer': {'name': 'Unknown Analyzer'},
                        'potential_vulnerabilities': [{'file': 'Unknown File',
                                                       'instances': [{'end_line': 656,
                                                                      'ref_id': 0,
                                                                      'start_line': 656}],
                                                       'type': 'integer_overflow'},
                                                      {'file': 'Unknown File',
                                                       'instances': [{'end_line': 776,
                                                                      'ref_id': 0,
                                                                      'start_line': 776},
                                                                     {'end_line': 740,
                                                                      'ref_id': 1,
                                                                      'start_line': 740}],
                                                       'type': 'call_to_external_contract'},
                                                      {'file': 'Unknown File',
                                                       'instances': [{'end_line': 776,
                                                                      'ref_id': 0,
                                                                      'start_line': 776}],
                                                       'type': 'multiple_calls'}],
                        'status': 'error'}],
 'audit_state': 5,
 'contract_hash': '7E794381F81684E8D633A47D1CDDE62BE1CA63A4F78F853E5EB81D8534463DB4',
 'status': 'error',
 'version': '2.0.1'}
```

The police node's report:
```
{'analyzers_reports': [{'analyzer': {'name': 'Unknown Analyzer'},
                        'potential_vulnerabilities': [{'file': 'Unknown File',
                                                       'instances': [{'end_line': 656,
                                                                      'ref_id': 0,
                                                                      'start_line': 656}],
                                                       'type': 'integer_overflow'},
                                                      {'file': 'Unknown File',
                                                       'instances': [{'end_line': 776,
                                                                      'ref_id': 0,
                                                                      'start_line': 776},
                                                                     {'end_line': 740,
                                                                      'ref_id': 1,
                                                                      'start_line': 740}],
                                                       'type': 'call_to_external_contract'},
                                                      {'file': 'Unknown File',
                                                       'instances': [{'end_line': 776,
                                                                      'ref_id': 0,
                                                                      'start_line': 776}],
                                                       'type': 'multiple_calls'}],
                        'status': 'success'}],
 'audit_state': 4,
 'contract_hash': '7E794381F81684E8D633A47D1CDDE62BE1CA63A4F78F853E5EB81D8534463DB4',
 'status': 'success',
 'version': '2.0.1'}
```

We're currently debating whether to treat different status as a major difference in the reports and do the "slashing". My take on it is that we probably shouldn't. We'll keep you posted on it.

**Comment by bbruijn** [comment]
Sorry should have zipped it the first time.
[Archief.zip](https://github.com/quantstamp/qsp-protocol-node/files/3249090/Archief.zip)
This log starts where the other one ended.
The directory .qsp-protocol is hidden by default, maybe something to add to the manual.

**Comment by alex-murashkin** [comment]
We are still not seeing the request id = 30 anywhere in the logs. Could you confirm that you have zipped the entire folder? My expectation is that there are `*.tar` files in that folder as well.

Also adding @arshdeeptinna - for suggestions on where to look for logs.

**Comment by alex-murashkin** [comment]
> Is there a way to check if my node is fully functioning now?

We are working on adding a so-called self-test for the node. The self-test would be a way of checking whether the node is operational and capable of performing actual scans.

Since your node successfully submitted the request id 26, I believe your node should be in a good state overall, and there was just some sort of a "fluke". The best course of actions for now is:
1. Look for more logs (@arshdeeptinna could assist with it)
2. Keep your node up and running. If your node is assigned another scan request, you'll be able to confirm.

On our side:
1. Implementing the self-test
2. Making it so that the node isn't slashed when only the report status has mismatched.
3. Investigating further if we receive more logs from you.

**Comment by alex-murashkin** [comment]
One other hypothesis: we are suspecting that default log level doesn't show all the log messages, and that could be why we aren't seeing all logs. I am confirming it with the team.

**Comment by bbruijn** [comment]
I think I submitted all the logs, there are 2 files in the directory .qsp-protocol 
![Schermafbeelding 2019-06-03 om 21 55 44](https://user-images.githubusercontent.com/11259481/58830331-60b9c500-864a-11e9-9182-3d4a7fe40cd9.png)

**Comment by alex-murashkin** [comment]
Thanks! There are some log messages that were not present in the original archive, however, still no log entries for request id 30. I will ask around to see if there is some logs that we are missing

**Comment by alex-murashkin** [comment]
In addition, could you also look for `event_database.db`? It should be somewhere in the user's home or the node's folder.

**Comment by bbruijn** [comment]
event database, again 2 versions. 
I wanted to make sure I had all the original files so I did a reinstall after the failed audit on Saturday. So included is the current version and the one from the trash
[Archief.zip](https://github.com/quantstamp/qsp-protocol-node/files/3249306/Archief.zip)

**Comment by bbruijn** [comment]
What should I look for in the logs as a search phrase to find request id 30? I can do some digging myself

**Comment by alex-murashkin** [comment]
You can look for `request_id`. It should have something like `"request_id": 26`, but the request id of 30.

**Comment by alex-murashkin** [comment]
Okay, we have found the request Id 30 in the DB file you shared. 
```
{
  "status": "error",
  "trace": [">> Wrapper setup finished\n", ">> Executing once is not needed. Skipping...\n", ">> Done\n", ">> About to execute pre_run script\n", "sha256:d1f683b3c561b382a86a1ca7d4d1df1d87986c23ee076345a9bf3679a7d707e3: Pulling from qspprotocol/securify-usolc\n", "Digest: sha256:d1f683b3c561b382a86a1ca7d4d1df1d87986c23ee076345a9bf3679a7d707e3\n", "Status: Image is up to date for qspprotocol/securify-usolc@sha256:d1f683b3c561b382a86a1ca7d4d1df1d87986c23ee076345a9bf3679a7d707e3\n", ">> Done\n", ">> Copying contract(s) to docker's mounted volume\n", ">> Done\n", ">> About to invoke securify\n"],
  "analyzer": {
    "name": "securify",
    "version": "d1f683b3c561b382a86a1ca7d4d1df1d87986c23ee076345a9bf3679a7d707e3",
    "vulnerabilities_checked": {
      "MissingInputValidation": {
        "type": "missing_input_validation"
      },
      "LockedEther": {
        "type": "locked_ether"
      },
      "UnrestrictedWrite": {
        "type": "unprotected_state_manipulation"
      },
      "UnrestrictedEtherFlow": {
        "type": "unprotected_ether_withdrawal"
      },
      "UnhandledException": {
        "type": "unchecked_call_return_value"
      },
      "DAO": {
        "type": "reentrancy"
      },
      "DAOConstantGas": {
        "type": "reentrancy"
      },
      "TODReceiver": {
        "type": "transaction_order_dependency"
      },
      "TODTransfer": {
        "type": "transaction_order_dependency"
      },
      "TODAmount": {
        "type": "transaction_order_dependency"
      },
      "MissingInputValidationTP": {
        "type": "missing_input_validation_true_positive"
      },
      "LockedEtherTP": {
        "type": "locked_ether_true_positive"
      },
      "UnrestrictedWriteTP": {
        "type": "unprotected_state_manipulation_true_positive"
      },
      "UnrestrictedEtherFlowTP": {
        "type": "unprotected_ether_withdrawal_true_positive"
      },
      "UnhandledExceptionTP": {
        "type": "unchecked_call_return_value_true_positive"
      },
      "DAOTP": {
        "type": "reentrancy_true_positive"
      },
      "DAOConstantGasTP": {
        "type": "reentrancy_true_positive"
      },
      "TODReceiverTP": {
        "type": "transaction_order_dependency_true_positive"
      },
      "TODTransferTP": {
        "type": "transaction_order_dependency_true_positive"
      },
      "TODAmountTP": {
        "type": "transaction_order_dependency_true_positive"
      },
      "SecurifyBug": {
        "type": "securify_bug"
      },
      "Unknown": {
        "type": "other"
      }
    },
    "command": "docker run --rm -v /tmp/securify/1196:/shared/ -i qspprotocol/securify-usolc@sha256:d1f683b3c561b382a86a1ca7d4d1df1d87986c23ee076345a9bf3679a7d707e3  -fs /shared/tmpwnt7bnta"
  },
  "start_time": 1559417243,
  "end_time": 1559417438
}]
}
```

According to the trace, it seems like the Securify analyzer has failed to start.
Could you double-check how much RAM is allocated for Docker (go to Preferences -> Advanced)? It looks like this:

<img width="381" alt="Screen Shot 2019-06-03 at 4 41 33 PM" src="https://user-images.githubusercontent.com/1721409/58833171-7c0edb00-861e-11e9-8938-19eedc823e53.png">

**Comment by bbruijn** [comment]
![Schermafbeelding 2019-06-03 om 22 46 02](https://user-images.githubusercontent.com/11259481/58833467-61a22500-8651-11e9-8df8-eaef138c1fd5.png)
It might be a bit low compared to your settings. I have 24 available. Should I set it to 5.2 GB?
I also found this: 
[securify.zip](https://github.com/quantstamp/qsp-protocol-node/files/3249428/securify.zip)

**Comment by martinetlee** [comment]
I think that is the problem!
It is suggested to set to 16GB according, this would likely decrease the failure caused by securify

**Comment by alex-murashkin** [comment]
Right! I think this is missing in the documentation: not only the machine needs to be at least 16 GB RAM, but also RAM allocation for Docker should be 16 GB. At least, that's what we've tested it with.

**Comment by bbruijn** [comment]
Thanks a lot guys, and yes you're right this was not in the manual. I bought extra RAM but never changed the docker preferences. I did now!
You might not get a lot of feedback from the community lately but I think you are doing an amazing job. I've been a supporter since 2017 and I'm really proud to be able to help. These are exciting times!

**Comment by martinetlee** [comment]
I created a PR for the manual to address this issue, thanks for discussing and solving the issue in detail with us, it is awesome to have you in our community @bbruijn! I'll close this issue since it is being resolved.
