### ISSUE TITLE
[BUG] `start-node` fail with `2/bin/common` on ubuntu

### ISSUE THREAD

**Issue by martinetlee** [quantstamp/qsp-protocol-node#502]
## Expected Behavior

start-node should succeed and start running the node, the user has incorporated the fix in the start-node
> open /bin/start-node and edit line 14, replace \"$0\" with "$0"?

## Current Behavior

`start-node` fail with `2/bin/common: No such file or directory` 

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version of this software: 2.0.2 beta2
* Operating System and version: Ubuntu, unknown version

## Additional Comments

I suspect it is the directory name, as there's a 2 before the /bin/common ...  asking the user to rename the directory so that it doesn't contain spaces.  -->  qsp_node_2.0.2_beta_2?

We might need to investigate how `realpath` works in Ubuntu.

**Comment by BravoNyN** [comment]
In order for me to run the node I placed the node folder in the home directory and not on desktop
Trying to run it straight from desktop fails to run the node

**Comment by ZakAyesh** [comment]
Renaming the directory to remove spaces worked, and my node is now running! Thanks Martin, this would probably be good to add to the guide to prevent people from making the same mistake.

**Comment by martinetlee** [comment]
NP, Zak!

I'm creating a ticket internally to investigate realpath behavior, but this would be low priority. 
In the meantime, the suggestion to keep the directory name without spaces is incorporated in an upcoming PR.

Closing this ticket as it is resolved. 

btw, it is Martinet here! :P
