### ISSUE TITLE
[BUG]The global event log in the protocol UI scrolls indefinitely on iOS safari

### ISSUE THREAD

**Issue by bbruijn** [quantstamp/qsp-protocol-node#504]
## Expected Behavior

When scrolling down on the desktop global event log in the protocol UI, you can scroll to the earliest log records. It works fine.

## Current Behavior

When you do the same on an Iphone, Safari gives you an infinite scrolling through the (before latest) log records. Chrome browser on Iphone skips records when scrolling down to older records.

## Steps to Reproduce

1. Example Chrome browser on iphone
![IMG_03F28B79320A-1](https://user-images.githubusercontent.com/11259481/59229942-32089500-8bdc-11e9-9c5f-38fe44324adc.jpeg)

2. Example safari browser on Iphone
![IMG_58656DAF5D50-1](https://user-images.githubusercontent.com/11259481/59230052-857ae300-8bdc-11e9-8b4a-cbc1af4c285a.jpeg)

3. Example first records on safari desktop
![Schermafbeelding 2019-06-11 om 00 06 45](https://user-images.githubusercontent.com/11259481/59230174-e9051080-8bdc-11e9-9a88-9448b24cfff6.png)

## Your Environment

* Version of this software:
* Operating System and version:
Iphone 6s on iOS 12.3.1

**Comment by alex-murashkin** [comment]
Thanks for reporting! A ticket has been created for this one, we'll try to address it.

**Comment by alex-murashkin** [comment]
Hey @bbruijn,

We've shipped a change that presumably fixes the issue.
Could you verify on your end as well?
Thanks!

**Comment by bbruijn** [comment]
Hi Alex,

Yes it works now. I can scroll all the way back to the first log events on safari (iPhone) now. 
Well done!

Bart

Verstuurd vanaf mijn iPhone

**Comment by alex-murashkin** [comment]
Fantastic, thanks for confirming! Closing this.
