### ISSUE TITLE
start-node fail jJSONDecodeError

### ISSUE THREAD

**Issue by dirkbekkers** [quantstamp/qsp-protocol-node#523]
I've been setting up the node. but the node is not starting. the log file is staying 0 KB.
So i start checking if my user has acces to the user group owner of docker. It has been added to the group.

I check the log file in .qsp-protocol but the log file stays at 0KB. the tar file only reports the output of end-node.

Thus i started to look further into the logs of the docker deamon  / protocol container. Here's what is happening:
<pre>docker container logs b77aaa017dd1
Thu Jun 27 18:19:10 UTC 2019
sha256:92bd41d22e72c9cb7af28dfa2784ead798916c115f59f1191fe45d6e4fabec4b: Pulling from qspprotocol/usolc-entry
Digest: sha256:92bd41d22e72c9cb7af28dfa2784ead798916c115f59f1191fe45d6e4fabec4b
Status: Image is up to date for qspprotocol/usolc-entry@sha256:92bd41d22e72c9cb7af28dfa2784ead798916c115f59f1191fe45d6e4fabec4b
Traceback (most recent call last):
  File &quot;/app/src/qsp_protocol_node/__main__.py&quot;, line 184, in &lt;module&gt;
    os.environ[&apos;QSP_LOGGING_LEVEL&apos;]
  File &quot;/app/src/qsp_protocol_node/__main__.py&quot;, line 119, in setup
    Program.__setup_log_streaming()
  File &quot;/app/src/qsp_protocol_node/__main__.py&quot;, line 95, in __setup_log_streaming
    keystore = load(k)
  File &quot;/usr/lib/python3.6/json/__init__.py&quot;, line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File &quot;/usr/lib/python3.6/json/__init__.py&quot;, line 354, in loads
    return _default_decoder.decode(s)
  File &quot;/usr/lib/python3.6/json/decoder.py&quot;, line 342, in decode
    raise JSONDecodeError(&quot;Extra data&quot;, s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 492 (char 491)
Restarting the audit node in 30s ..............................
Traceback (most recent call last):
  File &quot;/app/src/qsp_protocol_node/__main__.py&quot;, line 184, in &lt;module&gt;
    os.environ[&apos;QSP_LOGGING_LEVEL&apos;]
  File &quot;/app/src/qsp_protocol_node/__main__.py&quot;, line 119, in setup
    Program.__setup_log_streaming()
  File &quot;/app/src/qsp_protocol_node/__main__.py&quot;, line 95, in __setup_log_streaming
    keystore = load(k)
  File &quot;/usr/lib/python3.6/json/__init__.py&quot;, line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File &quot;/usr/lib/python3.6/json/__init__.py&quot;, line 354, in loads
    return _default_decoder.decode(s)
  File &quot;/usr/lib/python3.6/json/decoder.py&quot;, line 342, in decode
    raise JSONDecodeError(&quot;Extra data&quot;, s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 492 (char 491)
Restarting the audit node in 30s ..............................
</pre>
And so on....

I don't know if this is why the node is not starting up.but it is certainly trying to restart over and over.

Hope you can help me :-)

Best regards, Dirk

**Comment by dirkbekkers** [comment]
I found the problem, keystore had a syntax error. (default.json)

**Comment by martinetlee** [comment]
Glad you found the error! As an actionable, I would create a ticket internally to see if we could make this error easier for user to understand. Thanks for reporting!

**Comment by dirkbekkers** [comment]
node start up now takes long at:
{"message": "Executing securify's once script to download the image", "threadName": "MainThread", "lineno": 131, "pathname": "/app/src/qsp_protocol_node/audit/wrapper.py", "logger": "Wrapper", "level": "debug", "timestamp": "2019-06-27T19:11:46.167321Z"}
Is that normal?
