### ISSUE TITLE
Node Appears to Run, But is Failed

### ISSUE THREAD

**Issue by AncientAbysswalker** [quantstamp/qsp-protocol-node#543]
My node starts up and is indicated as running on the online GUI. That said, it appears to be not be working properly, as there are no proper logs or any work being done after a long time (weeks)

## Expected Behavior

Node runs, accepts work, outputs regular logs

## Current Behavior

Though currently shown as active on the GUI, there are no output logs in the log or nohup files. Using TMUX to permanently keep a terminal open to observe console output shows repeated messages indicating that new blocks are detected and that "No request available as the contract 0x5a0e27020FA22AdaB2e81495025bEF3Fab7821fd returned 2.". After a few rounds of it doing this it no longer outputs any further info.

## Your Environment
Ubuntu 16.04
[event_database.zip](https://github.com/quantstamp/qsp-protocol-node/files/3495220/event_database.zip)

**Comment by martinetlee** [comment]
"No request available as the contract" is a benign message that indicates there are no scan requests. Quoting from Alex: 

> Once there is a scan submitted to the network (like the one 30 mins ago) that matches the price criteria (the default is 1000 QSP), you should see a different message saying something like "A new scan is available", and your node will submit a transaction to try to self-assign it to the scan.

However, I believe it should continue to show such message if it didn't get scans. I've investigated the event_database and seems normal to me. Could you also provide the other logs? In any case, does it continue to show the message if you restart the software?

Best

**Comment by AncientAbysswalker** [comment]
I have restarted the node a couple times and it seems like the terminal output stops after a short period. In addition, the log file at ${HOME}/.qsp-protocol is empty...

Are there any other log locations I can check?

**Comment by martinetlee** [comment]
Not really, that is where we store the logs. Could you show all the messages on the console then? I'll also check with the team what other information might help.

**Comment by AncientAbysswalker** [comment]
Oddly enough I got it running for a day after a couple tries and it seemed to work. I need to upgrade to confirm it works now though

**Comment by martinetlee** [comment]
Sounds good, I'm closing this as this is resolved.
