### ISSUE TITLE
[BUG] Older already submitted audit report gets re-submitted after node update to 2.0.4

### ISSUE THREAD

**Issue by bbruijn** [quantstamp/qsp-protocol-node#549]
After updating my node to version 2.0.4 an already submitted report was re-submitted and led to an Invalid state for submission event in the UI
![Schermafbeelding 2019-08-21 om 15 38 43](https://user-images.githubusercontent.com/11259481/63437365-b1131880-c42a-11e9-9af5-b11d40eb2a2a.png)

## Expected Behavior

The report should not be re submitted after updating to a newer version of the protocol
## Steps to Reproduce

1.  ?
2.
3.
4.

## Your Environment

* Version of this software: 2.0.4
* Operating System and version: 
![Schermafbeelding 2019-08-21 om 15 43 08](https://user-images.githubusercontent.com/11259481/63437349-a6588380-c42a-11e9-8cae-9cf6102b5d2d.png)

## Additional Comments

transaction:
https://etherscan.io/tx/0x19c74d46dce2b852c205f89f4ac9de48f646051f00ee6ef71180ee40a43b46f3
[Archief.zip](https://github.com/quantstamp/qsp-protocol-node/files/3525595/Archief.zip)

**Comment by martinetlee** [comment]
Thanks for providing the logs Bart! I created a ticket internally. 
I've opened the logs and see a `qsp-protocol.log` and another `qsp-protocol.tar.gz` with a `qsp-protocol 2.log` inside.

Could you also provide the db logs? That would be very helpful as well!

https://github.com/quantstamp/qsp-protocol-node/blob/develop/doc/node-operator.md#view-logs

**Comment by bbruijn** [comment]
Could you please remind me where to find the db logs again?

**Comment by bbruijn** [comment]
[event_database.db.zip](https://github.com/quantstamp/qsp-protocol-node/files/3525697/event_database.db.zip)

**Comment by bbruijn** [comment]
Hello Sung, I have been searching but all I have is the event DB from the 2.0.3 directory which was active at 16th of August. My timemachine backup is not working properly so I dont have the qsp-protocol.log other than I already sent you.
[event_database.db.zip](https://github.com/quantstamp/qsp-protocol-node/files/3531310/event_database.db.zip)
