### ISSUE TITLE
[BUG] Tell the [The Protocol Contract] to freeze and stake the funds transation fails

### ISSUE THREAD

**Issue by jalme** [quantstamp/qsp-protocol-node#553]
When submiting the transaction to stake the funds it fails with error: 

![QSPerror](https://user-images.githubusercontent.com/26111993/68329936-4341c900-00ca-11ea-8310-2cf92c78b70d.png)

Expectation: Transaction goes throught with no error

## Current Behavior

I navigated to https://etherscan.io/address/0x5a0e27020fa22adab2e81495025bef3fab7821fd#writeContract to access the contract functions. Then submited the bellow information after connecting to metamask.

![Screenshot from 2019-11-06 19-20-34](https://user-images.githubusercontent.com/26111993/68330113-8f8d0900-00ca-11ea-80a3-f35b3e99baa4.png)

## Possible Solution

N/A

## Steps to Reproduce

See above

## Context
Was following instructions located at https://github.com/quantstamp/qsp-protocol-node/blob/develop/doc/node-operator.md#1-download-the-bundle
Currently I can't continue to install the node.

## Your Environment
Ubuntu 18.04.3 LTS
16 GB RAM
i7-8700K CPU @ 3.70GHz × 12

**Comment by alex-murashkin** [comment]
Hi,

1. Did you approve the protocol to spend the QSP tokens on your behalf? The step "Approve [The Protocol Contract] to withdraw QSP from you"

2. Also, could you double-check that you have sufficient QSP balance?

Thank you!

**Comment by jalme** [comment]
So point 2 makes sense... let me load the wallet with the needed QSP.... Will keep you posted.

**Comment by jalme** [comment]
Ok transaction went through. Might be good to put a hint on the steps to remember people to make sure there is QSP in the wallet :)

**Comment by jalme** [comment]
Thanks. QSP wallet needed QSP balance. All fixed.

**Comment by alex-murashkin** [comment]
Great, closing this!
