### ISSUE TITLE
Unstaking issue: "Please connect to your Web3 provider!"[BUG]

### ISSUE THREAD

**Issue by Dimensionsofahimsa** [quantstamp/qsp-protocol-node#556]
**Unstake** should "free" my tokens

Unstaking not functioning, so funds are locked

"etherscan.io says: Please connect to your Web3 provider!"

This is quite an issue since I'd need my funds.
Thank you

**Comment by Dimensionsofahimsa** [comment]
The contract:

[](https://etherscan.io/address/0x5a0e27020fa22adab2e81495025bef3fab7821fd)

**Comment by martinetlee** [comment]
Hi, have you connected to your web3 provider by clicking the [Connect to Web3] next to Write Contract?

<img width="565" alt="ScreenShot 2020-04-22 at 3 51 47 PM" src="https://user-images.githubusercontent.com/32376541/80027179-55b19280-84b1-11ea-9472-1d1650788197.png">

**Comment by Dimensionsofahimsa** [comment]
> Hi, have you connected to your web3 provider by clicking the [Connect to Web3] next to Write Contract?
> 
> <img alt="ScreenShot 2020-04-22 at 3 51 47 PM" width="565" src="https://user-images.githubusercontent.com/32376541/80027179-55b19280-84b1-11ea-9472-1d1650788197.png">

Awesome, thank you! The little tab seemed to take a longer time loading probably because of Brave.

If only the nodes were meant to be remote. Right now it's not practical

The issue can be marked resolved, thank you for such fast response

**Comment by martinetlee** [comment]
Glad that it worked! We understand the importance of having to be able to move funds freely.
