### ISSUE TITLE
[BUG]All nodes seem to become active and inactive on the dashboard

### ISSUE THREAD

**Issue by bbruijn** [quantstamp/qsp-protocol-node#557]
The protocol dashboard shows a constant variation in the number of active nodes. Somewhere between 1 and 10, fluctuating constantly. I noticed this today.
My node shows an error in the log which I have included below.

[qsp-protocol.zip](https://github.com/quantstamp/qsp-protocol-node/files/4702298/qsp-protocol.zip)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version of this software:
* Operating System and version:

**Comment by jalme** [comment]
Same on my side with the same error shown in log: 

`{"message": "No request available as the contract 0x5a0e27020FA22AdaB2e81495025bEF3Fab7821fd returned 2.", "threadName": "poll_requests thread", "lineno": 181, "pathname": "/app/src/qsp_protocol_node/audit/threads/poll_requests_thread.py", "logger": "PollRequestsThread", "level": "debug", "timestamp": "2020-05-31T20:49:43.379462Z"}
{"message": "Metrics sent successfully to 'https://protocol.quantstamp.com/node-metrics'", "threadName": "collect metrics thread", "lineno": 59, "pathname": "/app/src/qsp_protocol_node/utils/metrics.py", "metrics_json": {"processIdentifier": "ad22f8a96616-483", "ethBlockNumber": 10175847, "ethNodeVersion": "Geth/v1.9.9-omnibus-e320ae4c-20191206/linux-amd64/go1.13.4", "ethProtocolVersion": "64", "contractVersion": "2.9.1", "nodeVersion": "2.0.4", "hostCpu": 12.5, "hostMemory": 31.0, "hostDisk": 52.0, "minPrice": 1000, "account": "0x1FF48BBD7b1747F849B7B63282C8b83d6Ce35390"}, "headers": {"Content-type": "application/json", "User-agent": "Mozilla/5.0", "Authorization": "Digest: 0x5a5f4077ed6e59c45f2aa33629daf0364b67239235da28f64535a2b71ba9092052de5d1b7efa1dcf792fec507023a431d033951db08bbf3275dbb29d6bb62e681b"}, "response": "{\"status\":\"ok\",\"payload\":{}}", "logger": "MetricCollector", "level": "debug", "timestamp": "2020-05-31T20:49:45.210412Z"}
{"message": "Stopping QSP Audit Node", "threadName": "MainThread", "lineno": 315, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "info", "timestamp": "2020-05-31T20:49:48.190245Z"}
{"message": "Thread block_mined_polling thread is signaled to stop.", "threadName": "MainThread", "lineno": 321, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.190540Z"}
{"message": "Thread compute_gas_price thread is signaled to stop.", "threadName": "MainThread", "lineno": 321, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.190771Z"}
{"message": "Thread claim rewards thread is signaled to stop.", "threadName": "MainThread", "lineno": 321, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.190992Z"}
{"message": "Thread poll_requests thread is signaled to stop.", "threadName": "MainThread", "lineno": 321, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.191211Z"}
{"message": "Thread audit thread is signaled to stop.", "threadName": "MainThread", "lineno": 321, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.191401Z"}
{"message": "Thread submission thread is signaled to stop.", "threadName": "MainThread", "lineno": 321, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.191589Z"}
{"message": "Thread monitor thread is signaled to stop.", "threadName": "MainThread", "lineno": 321, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.191785Z"}
{"message": "Thread collect metrics thread is signaled to stop.", "threadName": "MainThread", "lineno": 321, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.191980Z"}
{"message": "Thread block_mined_polling thread is joined and stopped.", "threadName": "MainThread", "lineno": 331, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.192168Z"}
{"message": "Thread compute_gas_price thread is joined and stopped.", "threadName": "MainThread", "lineno": 331, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.263578Z"}
{"message": "Thread claim rewards thread is joined and stopped.", "threadName": "MainThread", "lineno": 331, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.263876Z"}
{"message": "Thread poll_requests thread is joined and stopped.", "threadName": "MainThread", "lineno": 331, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.287821Z"}
{"message": "Thread audit thread is joined and stopped.", "threadName": "MainThread", "lineno": 331, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.288132Z"}
{"message": "Thread submission thread is joined and stopped.", "threadName": "MainThread", "lineno": 331, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.288367Z"}
{"message": "Thread monitor thread is joined and stopped.", "threadName": "MainThread", "lineno": 331, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.288588Z"}
{"message": "Thread collect metrics thread is joined and stopped.", "threadName": "MainThread", "lineno": 331, "pathname": "/app/src/qsp_protocol_node/audit/audit.py", "logger": "QSPAuditNode", "level": "debug", "timestamp": "2020-05-31T20:49:48.288801Z"}
{"message": "Error in running node: Cannot proceed execution. At least one internal thread is not alive (<BlockMinedPollingThread(block_mined_polling thread, stopped 140084829997840)>)", "threadName": "MainThread", "lineno": 211, "pathname": "/app/src/qsp_protocol_node/__main__.py", "logger": "__main__", "level": "error", "timestamp": "2020-05-31T20:49:48.299138Z", "exception": "Traceback (most recent call last):\n  File \"/app/src/qsp_protocol_node/__main__.py\", line 208, in <module>\n    Program.run(os.environ['QSP_ETH_PASSPHRASE'], os.environ['QSP_ETH_AUTH_TOKEN'], sol_file)\n  File \"/app/src/qsp_protocol_node/__main__.py\", line 184, in run\n    raise error\n  File \"/app/src/qsp_protocol_node/__main__.py\", line 180, in run\n    audit_node.start()\n  File \"/app/src/qsp_protocol_node/audit/audit.py\", line 291, in start\n    self.__check_all_threads()\n  File \"/app/src/qsp_protocol_node/audit/audit.py\", line 307, in __check_all_threads\n    str(thread_lost))\nException: Cannot proceed execution. At least one internal thread is not alive (<BlockMinedPollingThread(block_mined_polling thread, stopped 140084829997840)>)"}
{"message": "Connected on attempt 0", "threadName": "MainThread", "lineno": 118, "pathname": "/app/src/qsp_protocol_node/config/config_utils.py", "logger": "ConfigUtils", "level": "debug", "timestamp": "2020-05-31T20:50:19.488755Z"}
{"message": "Executing mythril's once script to download the image", "threadName": "MainThread", "lineno": 131, "pathname": "/app/src/qsp_protocol_node/audit/wrapper.py", "logger": "Wrapper", "level": "debug", "timestamp": "2020-05-31T20:50:20.059588Z"}
{"message": "Executing securify's once script to download the image", "threadName": "MainThread", "lineno": 131, "pathname": "/app/src/qsp_protocol_node/audit/wrapper.py", "logger": "Wrapper", "level": "debug", "timestamp": "2020-05-31T20:50:21.441543Z"}
{"message": "Initializing QSP Audit Node", "threadName": "MainThread", "lineno": 151, "pathname": "/app/src/qsp_protocol_node/__main__.py", "logger": "__main__", "level": "info", "timestamp": "2020-05-31T20:50:22.717274Z"}
{"message": "account: 0x1FF48BBD7b1747F849B7B63282C8b83d6Ce35390", "threadName": "MainThread", "lineno": 152, "pathname": "/app/src/qsp_protocol_node/__main__.py", "logger": "__main__", "level": "debug", "timestamp": "2020-05-31T20:50:22.718705Z"}
{"message": "analyzers: [mythril, securify]", "threadName": "MainThread", "lineno": 153, "pathname": "/app/src/qsp_protocol_node/__main__.py", "logger": "__main__", "level": "debug", "timestamp": "2020-05-31T20:50:22.719598Z"}
{"message": "audit contract address: 0x5a0e27020FA22AdaB2e81495025bEF3Fab7821fd", "threadName": "MainThread", "lineno": 154, "pathname": "/app/src/qsp_protocol_node/__main__.py", "logger": "__main__", "level": "debug", "timestamp": "2020-05-31T20:50:22.720419Z"}
{"message": "min_price_in_qsp: 1000", "threadName": "MainThread", "lineno": 156, "pathname": "/app/src/qsp_protocol_node/__main__.py", "logger": "__main__", "level": "debug", "timestamp": "2020-05-31T20:50:22.720640Z"}
{"message": "evt_polling: 5", "threadName": "MainThread", "lineno": 157, "pathname": "/app/src/qsp_protocol_node/__main__.py", "logger": "__main__", "level": "debug", "timestamp": "2020-05-31T20:50:22.720828Z"}
{"message": "Running QSP node (performs audits only)", "threadName": "MainThread", "lineno": 167, "pathname": "/app/src/qsp_protocol_node/__main__.py", "logger": "__main__", "level": "info", "timestamp": "2020-05-31T20:50:23.040615Z"}
{"message": "Checking for any available rewards for address 0x1FF48BBD7b1747F849B7B63282C8b83d6Ce35390.", "threadName": "claim rewards thread", "lineno": 29, "pathname": "/app/src/qsp_protocol_node/audit/threads/claim_rewards_thread.py", "logger": "ClaimRewardsThread", "level": "info", "timestamp": "2020-05-31T20:50:23.687218Z"}
{"message": "There are no available rewards for address 0x1FF48BBD7b1747F849B7B63282C8b83d6Ce35390.", "threadName": "claim rewards thread", "lineno": 37, "pathname": "/app/src/qsp_protocol_node/audit/threads/claim_rewards_thread.py", "logger": "ClaimRewardsThread", "level": "info", "timestamp": "2020-05-31T20:50:24.181925Z"}
{"message": "New block detected: 10175850. Current gas price: 14641000000", "threadName": "compute_gas_price thread", "lineno": 21, "pathname": "/app/src/qsp_protocol_node/audit/threads/compute_gas_price_thread.py", "logger": "ComputeGasPriceThread", "level": "debug", "timestamp": "2020-05-31T20:50:24.429773Z"}
{"message": "No request available as the contract 0x5a0e27020FA22AdaB2e81495025bEF3Fab7821fd returned 2.", "threadName": "poll_requests thread", "lineno": 181, "pathname": "/app/src/qsp_protocol_node/audit/threads/poll_requests_thread.py", "logger": "PollRequestsThread", "level": "debug", "timestamp": "2020-05-31T20:50:24.813616Z"}
`

**Comment by martinetlee** [comment]
Hello @jalme . I have investigated the issue offline with @bbruijn , our current hypothesis is that this is caused by Infura throttling. 

What we could recommend now is to change the setting in this line:
https://github.com/quantstamp/qsp-protocol-node/blob/develop/resources/config.yaml#L71

We currently would suggest to change it to 5. it might not immediately solve the issue, but should see the impact after Infura stopped rate limiting your node.

The solution above has worked for a couple of node operators. Please let me know if the issue persists!  (Do remember to give it a little bit of time though!)

Thank you!
